# This will show the time on a 2nd line
# Add a "\" at the end of an item, if you want the next item to show on the same line
format = """
$sudo\
$username\
$hostname\
$all\
$directory
${env_var.yazi_level}\
$character
"""

[username]
style_user = '#248CD7 bold'
style_root = '#C94C15 bold'
format = '[$user]($style) '
show_always = true

[hostname]
ssh_only = true # El nombre de tu PC Solo se mostrara cuando uses ssh 
format = '@(white bold)[$hostname](#04d1f9 bold) '

[directory]
style = '#2C9F9D bold'
truncation_length = 0
truncate_to_repo = false

[character]
success_symbol = '[ó°˜](#37f499 bold)'
error_symbol = '[ï”¯](#f16c75 bold)'
vicmd_symbol = '[â®](#987afb bold)'

[env_var.yazi_level]
description = "Indicate the shell was launched by `yazi`"
variable = "YAZI_LEVEL"
style = '#F08A3F bold'
symbol = "î• ->ğŸ¦†"
format = '[ $symbol ]($style)'
